# Generated by Django 2.2.6 on 2019-10-18 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encargado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_task', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_entrega', models.DateField()),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encargado.Encargado')),
            ],
        ),
    ]
