# Generated by Django 2.2.6 on 2019-10-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_encargado', models.CharField(max_length=50)),
                ('apellido_encargado', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=10)),
                ('nombre_usuario', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]
